import { Metadata } from 'next';
import { Footer, Header } from '@/common';
import '@/styles/globals.scss';

export const metadata: Metadata = {
	title: '前端技术宅',
	description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<html lang="zh">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
};
export default RootLayout;
